//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ST.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReturnsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReturnsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ST.Resource.ReturnsResource", typeof(ReturnsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الوثيقة.
        /// </summary>
        public static string doclocnumDisplayName {
            get {
                return ResourceManager.GetString("doclocnumDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صافى الضريبة.
        /// </summary>
        public static string nettaxpyDisplayName {
            get {
                return ResourceManager.GetString("nettaxpyDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضريبة المشتريات.
        /// </summary>
        public static string purctdt2DisplayName {
            get {
                return ResourceManager.GetString("purctdt2DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال {0}..
        /// </summary>
        public static string RequiredMessage {
            get {
                return ResourceManager.GetString("RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الإقرار.
        /// </summary>
        public static string returncodeDisplayName {
            get {
                return ResourceManager.GetString("returncodeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم التسجيل.
        /// </summary>
        public static string rinDisplayName {
            get {
                return ResourceManager.GetString("rinDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string rinError {
            get {
                return ResourceManager.GetString("rinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضريبة المبيعات.
        /// </summary>
        public static string saleltcDisplayName {
            get {
                return ResourceManager.GetString("saleltcDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفترة الضريبية.
        /// </summary>
        public static string taxyrmoDisplayName {
            get {
                return ResourceManager.GetString("taxyrmoDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ المعاملة.
        /// </summary>
        public static string transdateDisplayName {
            get {
                return ResourceManager.GetString("transdateDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إقرار مبيعات.
        /// </summary>
        public static string viewCreateOrEditH2 {
            get {
                return ResourceManager.GetString("viewCreateOrEditH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبيعات.
        /// </summary>
        public static string viewCreateOrEditPurch {
            get {
                return ResourceManager.GetString("viewCreateOrEditPurch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المشتريات.
        /// </summary>
        public static string viewCreateOrEditSales {
            get {
                return ResourceManager.GetString("viewCreateOrEditSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string viewCreateOrEditSave {
            get {
                return ResourceManager.GetString("viewCreateOrEditSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string ViewDeleteButton {
            get {
                return ResourceManager.GetString("ViewDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد من الإلغاء؟.
        /// </summary>
        public static string viewDeleteMsg {
            get {
                return ResourceManager.GetString("viewDeleteMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة إقرار مبيعات.
        /// </summary>
        public static string viewIndexCreate {
            get {
                return ResourceManager.GetString("viewIndexCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string viewIndexDelete {
            get {
                return ResourceManager.GetString("viewIndexDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل.
        /// </summary>
        public static string viewIndexDetails {
            get {
                return ResourceManager.GetString("viewIndexDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل .
        /// </summary>
        public static string viewIndexEdit {
            get {
                return ResourceManager.GetString("viewIndexEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة إقرارات المبيعات.
        /// </summary>
        public static string viewIndexH2 {
            get {
                return ResourceManager.GetString("viewIndexH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة رقم الوثيقة.
        /// </summary>
        public static string viewIndexPrint {
            get {
                return ResourceManager.GetString("viewIndexPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        public static string viewIndexSend {
            get {
                return ResourceManager.GetString("viewIndexSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مشتريات.
        /// </summary>
        public static string viewRetPurchListAddPurch {
            get {
                return ResourceManager.GetString("viewRetPurchListAddPurch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مبيعات.
        /// </summary>
        public static string viewRetPurchListAddSales {
            get {
                return ResourceManager.GetString("viewRetPurchListAddSales", resourceCulture);
            }
        }
    }
}
